import turtle

# Create a turtle screen and set the background color to black
w = turtle.Screen()
w.bgcolor("black")

# Create a turtle pen named 'neha' and set its initial properties
neha = turtle.Pen()
neha.color("white")
neha.speed(0)
neha.up()
neha.setheading(180)
neha.goto(200, 0)
neha.down()

# Draw a rectangle filled with orange color
neha.begin_fill()
neha.fillcolor("orange")
neha.forward(400)
neha.setheading(0)
neha.setheading(90)
neha.forward(100)
neha.setheading(0)
neha.forward(400)
neha.setheading(270)
neha.forward(100)
neha.end_fill()

# Reset the turtle pen position and properties
neha.home()
neha.up()

# Draw a rectangle filled with green color
neha.setheading(270)
neha.goto(0, -100)
neha.setheading(0)
neha.goto(200, -100)
neha.setheading(270)
neha.down()
neha.begin_fill()
neha.fillcolor("green")
neha.forward(100)
neha.setheading(180)
neha.forward(400)
neha.setheading(90)
neha.forward(100)
neha.setheading(0)
neha.forward(400)
neha.end_fill()
neha.setheading(90)
neha.forward(100)
neha.back(100)
neha.setheading(180)
neha.forward(400)
neha.setheading(90)
neha.forward(100)

# Reset turtle pen position and properties
neha.up()
neha.home()

# Draw a circle filled with blue color 
neha.down()
neha.begin_fill()
neha.circle(-50)
neha.up()
neha.goto(0, -50)
neha.down()
q = 15
neha.fillcolor("blue")
for i in range(24):
    neha.forward(50)
    neha.bk(50)
    neha.left(q)
neha.end_fill()

# Reset turtle pen position and properties
neha.up()
neha.home()
neha.goto(0, 250)

# Drawing various shapes to form a pattern(INDIA)
neha.setheading(180)
neha.goto(-180, 250)
neha.down()
neha.setheading(0)
neha.forward(50)
neha.bk(25)
neha.setheading(270)
neha.forward(125)
neha.setheading(0)
neha.forward(25)
neha.bk(25)
neha.setheading(180)
neha.forward(25)
neha.backward(25)
neha.up()
neha.setheading(0)
neha.forward(55)
neha.setheading(90)
neha.down()
neha.forward(125)
neha.setheading(290)
neha.forward(132)
neha.setheading(90)
neha.forward(126)
neha.setheading(0)
neha.up()
neha.forward(30)
neha.down()
neha.setheading(270)
neha.forward(126)
neha.setheading(0)
neha.forward(50)
neha.setheading(90)
neha.forward(126)
neha.setheading(180)
neha.forward(50)
neha.bk(50)
neha.up()
neha.setheading(0)
neha.forward(30)
neha.down()
neha.forward(50)
neha.backward(25)
neha.setheading(270)
neha.forward(126)
neha.setheading(0)
neha.forward(25)
neha.bk(25)
neha.setheading(180)
neha.forward(25)
neha.setheading(0)
neha.up()
neha.forward(80)
neha.down()
neha.setheading(90)
neha.forward(126)
neha.setheading(0)
neha.forward(50)
neha.setheading(270)
neha.forward(126)
neha.bk(63)
neha.setheading(180)
neha.forward(50)

# Hide the turtle pen
neha.hideturtle()
